version: '3.7'
services:
  mysql:
    build:
      context: .
      dockerfile: dockerfile
    container_name: mysql
    restart: always
    ports:
    - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_my_data_base"
      MYSQL_USER: "userdb"
      MYSQL_PASSWORD: "userpwd"
    volumes:
      - ./schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge
