pipeline {
  agent { label 'newslave' }
  stages {
    stage ('Mostrar ruta de trabajo') {
      steps {
        script {
          sh "pwd"
        }
      }
    }
    stage ('listar archivos') {
      steps {
        script {
          sh "ls"
        }
      }
    }
  }
}
