pipeline {
  agent { label 'newslave' }
  stages {
    stage ('Ubicar los archivos para construir los contenedores') {
      steps {
        script {
          sh "ls Jenkins/docker/mysql"
        }
      }
    }
    stage ('Ejecutar los contenedores') {
      steps {
        script {
          sh "docker compose -f Jenkins/docker/mysql/docker-compose.yaml up -d"
        }
      }
    }
  }
}
