pipeline {
  agent { label 'newslave' }
  stages {
    stage ('Ubicar los archivos para construir los contenedores') {
      steps {
        script {
          sh "ls Jenkins/docker/mysql"
        }
      }
    }
    stage ('Mostrar archivos') {
      steps {
        script {
          sh "ls"
        }
      }
    }
  }
}
